metrics:
  interval: 10  # seconds

cloud:
  endpoint: "http://localhost:8000/api/metrics"
  api_key: "dev-local-key"

alerting:
  cpu_threshold: 90      # percent
  memory_threshold: 80   # percent
  disk_threshold: 80     # percent

influxdb:
  url: "http://localhost:8086"
  token: "demo-token"
  org: "demo-org"
  bucket: "metrics"
